### ISSUE TITLE
Add option to change the default "Out of Stock Message"

### ISSUE THREAD

**Issue by hchouhan** [flowdee/amazon-product-in-a-post-plugin#20]
Is there any methods available to customize the text displayed when product is out of stock?

**Comment by hchouhan** [comment]
https://secure.helpscout.net/conversation/1281859877/28640?folderId=2352906

**Comment by webdj-agency** [comment]
Sure, that's why the "in stock" / "out of stock" text is wrapped with wordpress "apply_filters" hook.
As the client described, he made changes directly in the plugin code with no guarantee after the plugin is updated.

The right way is to add this snippet at the very end of the client's child theme "functions.php" file:
```
add_filter( 'appip_text_instock',    function() { return "CUSTOM_IN_STOCK_MESSAGE"; } );
add_filter( 'appip_text_outofstock', function() { return "CUSTOM_OUT_OF_STOCK_MESSAGE"; } );
```
