### ISSUE TITLE
Button Image not loading when using grid shortcode

### ISSUE THREAD

**Issue by hchouhan** [flowdee/amazon-product-in-a-post-plugin#9]
The Button image does not load as no image path is set.

<img width="954" alt="Screenshot 2020-05-29 12 34 25" src="https://user-images.githubusercontent.com/1587151/83224901-bfa41280-a1a8-11ea-93e9-247095509c7a.png">

@webdj-agency

**Comment by webdj-agency** [comment]
The template involves an variable `buyamzonbutton` which is undefined here.
This variable is in use as global var in other file and should be accessible from everywhere but it don't.
We asked the previous plugin owner to provide info about that

**Comment by flowdee** [comment]
Reply from the previous dev:

It was something that goes back to version 5.0 and has been missing since the plugin API version update.

You will need to add this to after line 149 of `inc/amazon-product-in-a-post-shortcode-grid.php`

`$buyamzonbutton = apply_filters( 'appip_amazon_button_url', $atts[ 'button_url' ], '', $atts[ 'locale' ] );`

This can go right after line 149 which is currently:
`/* END New Button functionality */`

**Comment by webdj-agency** [comment]
yes, fixed

**Comment by flowdee** [comment]
Cool!

Then we are going to release our first update on Monday/Tuesday @hchouhan

**Comment by flowdee** [comment]
FYI @hchouhan fixed with release of v5.1.1 today

**Comment by flowdee** [comment]
oops 👯‍♀️
